<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>jess</string>
		<string>jessy</string>
	</array>
	<key>name</key>
	<string>Jessy</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.jessy</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*#.*$\n?</string>
			<key>name</key>
			<string>comment.line.jessy</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>meta.property.jessy</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.quote.jessy</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.name.jessy</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.quote.jessy</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.equals.jessy</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>meta.value.jessy</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.quote.jessy</string>
				</dict>
				<key>8</key>
				<dict>
					<key>name</key>
					<string>string.name.value.jessy</string>
				</dict>
				<key>9</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.quote.jessy</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(\s*(["']?)(.+?)(\2)\s*(:))?\s*((["']?)(.*?)(\7))\s*$\n?</string>
			<key>name</key>
			<string>meta.declaration.jessy</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.jess</string>
</dict>
</plist>
